[package]
name = "structured_digest"
version = "0.1.0"
authors = ["Robin Marchart <robin.marchart@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
digest = "0.9.0"
